version: '3.4'
services:
  redis:
    image: redis:5.0-alpine
    ports:
      - "63790:6379"
    restart: unless-stopped
    command: sleep infinity
    network_mode: host
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    ports:
      - "54320:5432"
    restart: unless-stopped
    command: sleep infinity
    network_mode: host
  vets-api:
    build:
      context: .
      args:
        sidekiq_license: "${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}"
        userid: "${VETS_API_USER_ID}"
    image: "vets-api:${DOCKER_IMAGE:-latest}"
    command: >
      bash -c "bundle exec rake db:migrate || bundle exec rake db:setup db:migrate
      && touch tmp/caching-dev.txt && foreman start -m all=1,clamd=0,freshclam=0"
    volumes:
      - ../../../vets-api:/srv/vets-api/src:cached
      # - ./settings.local.yml:/srv/vets-api/config/settings.local.yml
      - ../../../vets-api-mockdata:/cache
      - dev_bundle:/usr/local/bundle
    ports:
      - "3000:3000"
      - "26162:26162"
      - "1234:1234"
      - "58430-58450:58430-58450"
    environment:
      "Settings.saml.authn_requests_signed": "false"
      "Settings.database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_development}?pool=4"
      "Settings.test_database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-vets_api_test}?pool=4"
      "Settings.redis.app_data.url": "redis://redis:6379"
      "Settings.redis.sidekiq.url": "redis://redis:6379"
      "Settings.redis.rails_cache.url": "redis://redis:6379"
      "Settings.binaries.clamdscan": "clamscan" # Not running a separate process within the container for clamdscan, so we use clamscan which requires no daemon
      POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    restart: unless-stopped
    network_mode: host
volumes:
  db-data:
  dev_bundle:
