services:
  node:
    image: tugboatqa/node:14
    default: true
    expose: 3001
    commands:
      init:
        - mkdir -p /etc/service/node
        - echo "#!/bin/sh" > /etc/service/node/run
        - echo "npm --prefix=$TUGBOAT_ROOT run heroku-serve -- build/localhost -p 3001" >> /etc/service/node/run
        - chmod +x /etc/service/node/run
      build:
        - yarn
        - yarn build --host=0.0.0.0 --public=$TUGBOAT_DEFAULT_SERVICE_URL_HOST
      start:
        - yarn watch &