name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ "gha-runner-docker-build" ]
    
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem
    steps:
    - name: Build
      run: |
        echo "Beginning free space:"
        df -h
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 33792
        remove-dotnet: 'true'
        remove-android: 'true'
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "Ending free space:"
        df -h

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dsva/preview-environment/vets-website
        IMAGE_TAG: front-end-latest
      run: |
        docker build -f Dockerfile1 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
