name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ "new-docker" ]
    
jobs:

  build:

    runs-on: self-hosted
    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: find ssl certs
      run: ls /etc/ssl/certs
    - name: Set PEM file content as environment variable
      
    - name: Copy PEM file to Docker build context
      run: cp /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem ${{ github.workspace }}/docker-build-context

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dsva/preview-environment/vets-website
        IMAGE_TAG: front-end-latest
      run: |
        docker build -f Dockerfile1 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
