name: Document Publish

on:
  workflow_run:
    workflows: [Build and Test]
    types: [completed]
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
    
    - name: Install dependencies in react-components
      run: yarn install
    
    - name: Build package NPM package
      run: yarn build

    - name: Build Documents
      run: yarn docs:build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: ${{ secrets.BJ_TEST_TOKEN }}
        publish_dir: ./docs
        publish_branch: master
        keep_files: true